name: appdata
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  intl: ^0.20.2
  dio: ^5.4.3+1
  curved_navigation_bar: ^1.0.6
  mobile_scanner: ^5.2.3
  go_router: 15.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  flutter_spinkit: 5.2.1
  encrypt: ^5.0.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-KI.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/logo_into.png"